config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "words#index"
  resources :words, only: [:index, :new, :create, :show, :edit, :update, :destroy]       # %i[index new create] both are same method to write
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :words
    validates :name, presence: true
    validates :name, inclusion: { in: LanguageList::COMMON_LANGUAGES.map(&:name) }
end

app/models/translation.rb
class Translation < ApplicationRecord
    belongs_to :word
    belongs_to :translated_word, class_name: 'Word'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :words
end

app/models/word.rb
class Word < ApplicationRecord
    belongs_to :language
    belongs_to :user

    has_many :transalations_association, class_name: 'Translation'
    has_many :translations, through: :transalations_association, source: :translated_word
    has_many :inverse_translations_association, class_name: 'Translation', foreign_key: 'translated_word_id'
    has_many :inverse_translations, through: :inverse_translations_association, source: :word

    validates :content, :language, presence: true

    paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_back(fallback_location: root_path)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    # before_action call the method which is described. just before perform the actual actions.
    before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
    before_action :set_method, only: %i[show edit update destroy]    
    
    def index
        @words = Word.page(params[:page])
    end

    def new
        @word = Word.new
    end

    def create
        @word = Word.new(word_params)
        @word.user = current_user
        if @word.save
            redirect_to(words_path)
        else
            render :new
        end
    end
    def word_params
        params.require(:word).permit(:content, :language_id)
    end
    
    def show; end       # you can delete or write with semicolumn if action is empty

    def edit
        authorize @word
    end

    def update
        # @word = Word.find(params[:id])     We call this line in set method.
        authorize @word
        if @word.update(word_params)
            redirect_to(word_path(@word))
        else
            render :edit
        end
    end

    def destroy
        # @word = Word.find(params[:id])
        authorize @word
        @word.destroy
        redirect_to(words_path)
    end

    def set_method
        @word = Word.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AngiplApplication
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
  %body
    .container
      = render "shared/navs"
      = render "shared/message"
      = yield

app/views/shared/_message.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert"}
    %ul
      %li
        = value

app/views/shared/_navs.html.haml
.container-fluid
    .row
    .col-md-12
        %ul.nav
            %li.nav-item
                = link_to('Home', root_path, class: 'nav-link')
            %li.nav-item
                = link_to('Create New Word', new_word_path, class: 'nav-link')
            - if user_signed_in?
                %li.nav-item
                    = link_to('Edit Registration', edit_user_registration_path, class: 'nav-link')
            - else
                %li.nav-item
                    = link_to('New Registration', new_user_registration_path, class: 'nav-link')
            - if user_signed_in?
                %li.nav-item
                    = button_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete)
            - else
                %li.nav-item
                    = link_to('Login', new_user_session_path, class: 'nav-link')
                -# %a.nav-link.disabled{href: "#"} Messages
            -# %li.nav-item.dropdown.ml-md-auto
            -#     %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"data-toggle" => "dropdown", href: "http://example.com"} Dropdown link
            -#     .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
            -#         %a.dropdown-item{href: "#"} Action
            -#         %a.dropdown-item{href: "#"} Another action
            -#         %a.dropdown-item{href: "#"} Something else here
            -#         .dropdown-divider
            -#         %a.dropdown-item{href: "#"} Separated link

app/views/words/_form.html.haml
= simple_form_for @word do |f|
  = f.input :content
  = f.association :language
  = f.button :submit, class: 'btn btn-primary'


-# %form{role: "form"}
-#   .form-group
-#     %label
-#       Email address
-#       %input#exampleInputEmail1.form-control{type: "email"}/
-#     .form-group
-#     %label
-#       Password
-#       %input#exampleInputPassword1.form-control{type: "password"}/
-#     %button.btn.btn-primary{type: "submit"}
-#       Submit

app/views/words/edit.html.haml
%h1 Edit Word

= render 'form'

app/views/words/index.html.haml
%h1 Words
%table.table
    %thead
        %tr.table-active
            %th
                ID
            %th
                CONTENT
            %th
                LANGUAGE
            %th
                USER
            %th 
                ACTION
            %th
                DELETE
        %tbody
            - @words.each do |word|
                %tr.table-success
                    %td
                        = word.id
                    %td
                        = word.content
                    %td
                        = word.language&.name
                        -# - if word.language
                        -#     = word.language.name
                    %td
                        = word.user&.email
                    %td
                        = link_to("Show", word_path(word), class: 'btn btn-primary')
                        = link_to("Edit", edit_word_path(word), class: 'btn btn-primary')
                        -# = link_to("Delete", word_path(word),  
                        -#     "turbo-method": :delete, 
                        -#     class: 'btn btn-primary')
                    %td
                        = button_to("Delete", word_path(word), method: :delete, class: 'btn btn-primary')

= paginate @words, theme: 'twitter-bootstrap-4'

app/views/words/new.html.haml
%h1 Word Form

= render 'form'

app/views/words/show.html.haml
%h1 Word
%p
 = @word.content
%p
 = @word.language&.name